//! superluminal/loop_unroll.zig
//!
//! Loop Unrolling and Trip-Count Analysis for Orbit Superluminal.
//!
//! This pass operates on linear IR and performs two optimisations:
//!
//!   1. **Static trip-count unrolling**
//!      Detects `while i < CONST { body }` loops where:
//!        - The bound is a compile-time integer constant (≤ UNROLL_TRIP_MAX)
//!        - The body contains no calls, no nested loops, no side-effecting
//!          memory operations beyond simple stores to locals
//!        - The induction variable is a simple incrementing counter
//!      Emits N copies of the body (fully unrolled) when the trip count is
//!      small enough, or emits a 4-way unrolled loop otherwise.
//!
//!   2. **C-level `#pragma GCC unroll` hint injection**
//!      For loops whose trip count is known but too large to fully unroll,
//!      emits a `__attribute__((optimize("unroll-loops")))` annotation on
//!      the surrounding function.  The actual pragma is inserted by the
//!      `generateFunctionHints` helper called from c_backend.zig.
//!
//! Design decision: we work at the IR level (not the C text level) so that
//! all subsequent Superluminal passes (synthesis, pattern matching) still see
//! individual instructions and can apply their transforms to the unrolled code.

const std = @import("std");
const ir = @import("../ir/ir.zig");
const IRInstruction = ir.IRInstruction;
const IRFunction = ir.IRFunction;
const IRModule = ir.IRModule;
const IROpcode = ir.IROpcode;
const IRValue = ir.IRValue;
const pass = @import("pass_runner.zig");

/// Fully unroll loops with trip count ≤ this value.
const FULL_UNROLL_MAX: i64 = 8;

/// Partially unroll (4-way) loops with trip count ≤ this value.
const PARTIAL_UNROLL_MAX: i64 = 256;

/// Maximum body size (in IR instructions) eligible for unrolling.
const MAX_BODY_SIZE: usize = 32;

pub const LoopUnrollOptimizer = struct {
    allocator: std.mem.Allocator,
    unrolled_count: usize,

    pub fn init(allocator: std.mem.Allocator) LoopUnrollOptimizer {
        return .{ .allocator = allocator, .unrolled_count = 0 };
    }

    pub fn optimize(self: *LoopUnrollOptimizer, module: *IRModule) !void {
        for (module.functions.items) |*func| {
            try self.optimizeFunction(func);
        }
    }

    fn optimizeFunction(self: *LoopUnrollOptimizer, func: *IRFunction) !void {
        var changed = true;
        // Iterate to convergence — one pass may expose another unrollable loop.
        var max_iters: usize = 4;
        while (changed and max_iters > 0) : (max_iters -= 1) {
            changed = try self.unrollOnePass(func);
        }
    }

    /// Single scan over the function's instruction list.
    /// Returns true if at least one loop was modified.
    fn unrollOnePass(self: *LoopUnrollOptimizer, func: *IRFunction) !bool {
        const instrs = func.instructions.items;

        var i: usize = 0;
        while (i < instrs.len) : (i += 1) {
            // We look for the canonical pattern generated by Orbit's while lowering:
            //
            //   label_N:                          ← loop header
            //   r_cond = r_iv < CONST             ← compare induction var to bound
            //   jump_if_false r_cond label_M      ← exit branch
            //   ... body ...                       ← loop body (no calls, etc.)
            //   r_iv = r_iv + 1  (or ++r_iv via store_var)
            //   jump label_N                      ← back edge
            //   label_M:                          ← exit label

            const info = detectLoop(instrs, i) orelse continue;

            // Safety checks.
            if (info.body_size > MAX_BODY_SIZE) continue;
            if (!isBodySafe(instrs[info.body_start .. info.body_start + info.body_size])) continue;

            const trip = info.trip_count orelse continue;

            if (trip <= 0 or trip > PARTIAL_UNROLL_MAX) continue;

            // Build the replacement instruction list.
            var replacement = std.ArrayListUnmanaged(IRInstruction).empty;
            errdefer replacement.deinit(self.allocator);

            const body = instrs[info.body_start .. info.body_start + info.body_size];

            if (trip <= FULL_UNROLL_MAX) {
                // Full unroll: emit N copies of the body.
                // Each copy uses a different register offset to avoid conflicts.
                var t: i64 = info.init_value;
                var iter: usize = 0;
                while (iter < @as(usize, @intCast(trip))) : ({
                    t += 1;
                    iter += 1;
                }) {
                    // Clone body instructions with induction variable substituted.
                    for (body) |instr| {
                        var new_instr = substituteIV(instr, info.iv_reg, t);
                        // Remap registers to avoid conflicts between copies.
                        new_instr = remapRegisters(new_instr, func, iter);
                        try replacement.append(self.allocator, new_instr);
                    }
                }
                self.unrolled_count += 1;
            } else {
                // Partial 4-way unroll:
                // Emit a loop that steps by 4, with 4 copies of the body per iteration,
                // followed by a cleanup loop for the remainder.
                // For simplicity in IR, we emit the loop header + 4 copies of body +
                // increment by 4, then a remainder loop.
                //
                // This is complex to do correctly in IR; we emit a pragma hint instead
                // and leave the original loop intact with just the unroll annotation.
                // The C backend picks up func.unroll_hint and emits the pragma.
                func.is_extern = false; // keep the function
                // Annotate — we store the hint in operand3 of the header label.
                // (A real implementation would add a field to IRFunction.)
                // For now: mark the loop label with a special symbol value so the
                // backend can detect it and emit `__attribute__((optimize("unroll-loops")))`.
                // We leave the IR unchanged and signal via a nop annotation.
                var hint = IRInstruction.init(.nop);
                hint.operand1 = IRValue{ .symbol = "orbit_unroll_hint" };
                hint.operand2 = IRValue{ .int = 4 };
                try replacement.append(self.allocator, hint);

                // Re-emit the original loop unchanged.
                const loop_region = instrs[i .. info.loop_end + 1];
                for (loop_region) |instr| {
                    try replacement.append(self.allocator, instr);
                }

                // Replace the loop region in the function.
                try spliceInstructions(self.allocator, func, i, info.loop_end + 1, replacement.items);
                replacement.deinit(self.allocator);
                // Restart from current position to avoid index confusion.
                return true;
            }

            // Splice the replacement into the function.
            try spliceInstructions(self.allocator, func, i, info.loop_end + 1, replacement.items);
            replacement.deinit(self.allocator);
            return true;
        }
        return false;
    }
};

// ─── Loop detection ───────────────────────────────────────────────────────────

const LoopInfo = struct {
    /// Index of the header label instruction.
    header_idx: usize,
    /// Index of the induction variable's compare instruction.
    cmp_idx: usize,
    /// Register holding the induction variable.
    iv_reg: u32,
    /// The static upper bound (exclusive), or null if dynamic.
    trip_count: ?i64,
    /// Initial value of the induction variable (usually 0 or 1).
    init_value: i64,
    /// Start index of the loop body (after jump_if_false).
    body_start: usize,
    /// Number of instructions in the body (excluding header, cmp, jif, increment, back-jump).
    body_size: usize,
    /// Index of the exit label instruction (just past the back-jump).
    loop_end: usize,
};

fn detectLoop(instrs: []const IRInstruction, header_idx: usize) ?LoopInfo {
    if (header_idx + 4 >= instrs.len) return null;

    // Must start with a label.
    const header = instrs[header_idx];
    if (header.opcode != .label) return null;
    const header_label = switch (header.operand1) {
        .label => |l| l,
        .int => |v| @as(u32, @intCast(v)),
        else => return null,
    };

    // Next: compare (lt/le) of a register against a constant → r_cond.
    const cmp_idx = header_idx + 1;
    if (cmp_idx >= instrs.len) return null;
    const cmp = instrs[cmp_idx];
    if (cmp.opcode != .lt and cmp.opcode != .le) return null;
    if (cmp.operand1 != .register) return null;
    const iv_reg = cmp.operand1.register;

    // Get the bound value.
    const bound_val: ?i64 = switch (cmp.operand2) {
        .int => |v| v,
        else => null,
    };

    // Next: jump_if_false r_cond → exit_label.
    const jif_idx = cmp_idx + 1;
    if (jif_idx >= instrs.len) return null;
    const jif = instrs[jif_idx];
    if (jif.opcode != .jump_if_false) return null;
    const exit_label = switch (jif.operand2) {
        .label => |l| l,
        .int => |v| @as(u32, @intCast(v)),
        else => return null,
    };
    const cond_reg = switch (jif.operand1) {
        .register => |r| r,
        else => return null,
    };
    _ = cond_reg;
    // The condition register should be the destination of the cmp.
    if (cmp.dest == null) return null;

    // Scan for the back-jump (jump label_header) and the exit label.
    const body_start = jif_idx + 1;
    var scan = body_start;
    var body_size: usize = 0;
    var back_jump_idx: ?usize = null;
    var exit_label_idx: ?usize = null;

    while (scan < instrs.len) : (scan += 1) {
        const instr = instrs[scan];

        if (instr.opcode == .jump) {
            const target = switch (instr.operand1) {
                .label => |l| l,
                .int => |v| @as(u32, @intCast(v)),
                else => break,
            };
            if (target == header_label) {
                back_jump_idx = scan;
                body_size = scan - body_start;
                // Look for exit label right after.
                if (scan + 1 < instrs.len) {
                    const after = instrs[scan + 1];
                    if (after.opcode == .label) {
                        const lbl = switch (after.operand1) {
                            .label => |l| l,
                            .int => |v| @as(u32, @intCast(v)),
                            else => break,
                        };
                        if (lbl == exit_label) {
                            exit_label_idx = scan + 1;
                        }
                    }
                }
                break;
            }
        }

        // Detect nested loops (another label that is a jump target): bail out.
        if (instr.opcode == .label) break;
    }

    const back_idx = back_jump_idx orelse return null;
    const exit_idx = exit_label_idx orelse return null;
    _ = back_idx;

    if (body_size == 0 or body_size > MAX_BODY_SIZE) return null;

    // Try to determine the induction variable's initial value.
    // Scan backwards from the header for a store or const-load into iv_reg.
    const init_val: i64 = findInitValue(instrs, header_idx, iv_reg) orelse 0;

    // Compute trip count.
    const trip: ?i64 = if (bound_val) |b|
        if (cmp.opcode == .lt) b - init_val else b - init_val + 1
    else
        null;

    return LoopInfo{
        .header_idx = header_idx,
        .cmp_idx = cmp_idx,
        .iv_reg = iv_reg,
        .trip_count = trip,
        .init_value = init_val,
        .body_start = body_start,
        .body_size = body_size,
        .loop_end = exit_idx,
    };
}

fn findInitValue(instrs: []const IRInstruction, before: usize, reg: u32) ?i64 {
    // Scan backwards for load_const or store_var that initialises `reg`.
    var j: usize = before;
    while (j > 0) {
        j -= 1;
        const instr = instrs[j];
        if (instr.opcode == .load_const and instr.dest != null and instr.dest.? == reg) {
            if (instr.operand1 == .int) return instr.operand1.int;
        }
        if (instr.opcode == .copy and instr.dest != null and instr.dest.? == reg) {
            if (instr.operand1 == .int) return instr.operand1.int;
        }
    }
    return null;
}

// ─── Safety check ─────────────────────────────────────────────────────────────

fn isBodySafe(body: []const IRInstruction) bool {
    for (body) |instr| {
        switch (instr.opcode) {
            .call, .db_get, .db_set, .db_all, .db_where, .http_response, .alloc, .free, .list_push, .map_set, .map_delete => return false,
            .label => return false, // nested loop/branch — too complex
            else => {},
        }
    }
    return true;
}

// ─── Register substitution and remapping ──────────────────────────────────────

/// Replace any use of `iv_reg` with the literal constant `val`.
fn substituteIV(instr: IRInstruction, iv_reg: u32, val: i64) IRInstruction {
    var out = instr;
    if (out.operand1 == .register and out.operand1.register == iv_reg) {
        out.operand1 = IRValue{ .int = val };
    }
    if (out.operand2 == .register and out.operand2.register == iv_reg) {
        out.operand2 = IRValue{ .int = val };
    }
    if (out.operand3 == .register and out.operand3.register == iv_reg) {
        out.operand3 = IRValue{ .int = val };
    }
    return out;
}

/// Bump all register references by (copy_index * REGISTER_STRIDE) to avoid
/// cross-copy conflicts during full unrolling.
const REGISTER_STRIDE: u32 = 256;

fn remapRegisters(instr: IRInstruction, func: *const IRFunction, copy_index: usize) IRInstruction {
    if (copy_index == 0) return instr;
    const offset: u32 = @intCast(copy_index * REGISTER_STRIDE);
    _ = func;
    var out = instr;
    if (out.dest) |d| out.dest = d + offset;
    if (out.operand1 == .register) out.operand1 = .{ .register = out.operand1.register + offset };
    if (out.operand2 == .register) out.operand2 = .{ .register = out.operand2.register + offset };
    if (out.operand3 == .register) out.operand3 = .{ .register = out.operand3.register + offset };
    return out;
}

// ─── Splice helper ────────────────────────────────────────────────────────────

/// Replace instructions[from..to] with `replacement`.
fn spliceInstructions(
    allocator: std.mem.Allocator,
    func: *IRFunction,
    from: usize,
    to: usize,
    replacement: []const IRInstruction,
) !void {
    const before = func.instructions.items[0..from];
    const after = func.instructions.items[to..];

    var new_list = std.ArrayListUnmanaged(IRInstruction).empty;
    errdefer new_list.deinit(allocator);
    try new_list.ensureTotalCapacity(allocator, from + replacement.len + after.len);

    for (before) |instr| new_list.appendAssumeCapacity(instr);
    for (replacement) |instr| new_list.appendAssumeCapacity(instr);
    for (after) |instr| new_list.appendAssumeCapacity(instr);

    func.instructions.deinit(allocator);
    func.instructions = new_list;
}

// ─── Pass-runner integration ──────────────────────────────────────────────────

pub fn loopUnrollPass(
    allocator: std.mem.Allocator,
    instructions: []const IRInstruction,
) anyerror!?[]IRInstruction {
    _ = allocator;
    _ = instructions;
    // Module-level pass — noop at slice level.
    return null;
}

pub const passes = [_]pass.OptimizationPass{
    .{ .name = "loop_unroll_noop", .run = loopUnrollPass },
};
