static ASTNode* parseFunctionDecl(Parser* parser, orbit_bool isPrivate, orbit_bool isExtern) {
    Parser* r_0;
    orbit_bool r_1;
    orbit_bool r_2;
    Parser* r_3;
    TokType r_4;
    orbit_bool r_5;
    Parser* r_6;
    TokType r_7;
    orbit_bool r_8;
    Parser* r_9;
    TokType r_10;
    orbit_string r_11;
    void* r_12;
    Parser* r_13;
    Token* r_14;
    orbit_string r_15;
    Parser* r_16;
    OrbitList* r_17;
    Parser* r_18;
    TokType r_19;
    orbit_string r_20;
    void* r_21;
    OrbitList* r_22;
    OrbitList* r_23;
    Parser* r_24;
    TokType r_25;
    orbit_bool r_26;
    orbit_bool r_27;
    orbit_bool r_28;
    orbit_bool r_29;
    void* r_30;
    Parser* r_31;
    TokType r_32;
    orbit_string r_33;
    void* r_34;
    Parser* r_35;
    Token* r_36;
    orbit_string r_37;
    void* r_38;
    orbit_string r_39;
    orbit_string r_41;
    Parser* r_42;
    TokType r_43;
    orbit_bool r_44;
    orbit_bool r_45;
    Parser* r_46;
    TokType r_47;
    orbit_bool r_48;
    orbit_bool r_49;
    Parser* r_50;
    orbit_string r_51;
    void* r_52;
    orbit_string r_53;
    orbit_string r_54;
    orbit_string r_55;
    void* r_56;
    void* r_57;
    Parser* r_59;
    TokType r_60;
    orbit_bool r_61;
    orbit_bool r_62;
    Parser* r_63;
    TokType r_64;
    orbit_string r_65;
    void* r_66;
    orbit_string r_67;
    Parser* r_68;
    TokType r_69;
    orbit_bool r_70;
    orbit_bool r_71;
    Parser* r_72;
    TokType r_73;
    orbit_bool r_74;
    orbit_bool r_75;
    Parser* r_76;
    orbit_string r_77;
    void* r_78;
    orbit_string r_79;
    orbit_string r_80;
    orbit_string r_81;
    OrbitList* r_82;
    void* r_83;
    void* r_84;
    Parser* r_85;
    TokType r_86;
    orbit_bool r_87;
    Parser* r_88;
    ASTNode* r_89;
    orbit_bool r_90;
    orbit_bool r_91;
    orbit_bool r_92;
    Parser* r_93;
    orbit_string r_94;
    void* r_95;
    orbit_string r_96;
    void* r_97;
    void* r_98;
    void* r_99;
    void* r_100;
    orbit_bool r_101;
    orbit_bool r_102;
    orbit_bool r_103;
    OrbitList* r_104;
    void* r_105;
    void* r_106;
    uintptr_t isAsync = 0;
    uintptr_t name = 0;
    uintptr_t genericParams = 0;
    uintptr_t params = 0;
    uintptr_t paramTypes = 0;
    uintptr_t parsingParams = 0;
    uintptr_t paramName = 0;
    uintptr_t paramType = 0;
    uintptr_t isPointer = 0;
    uintptr_t returnType = 0;
    uintptr_t isPointerReturn = 0;
    uintptr_t body = 0;
    r_0 = (void*)(uintptr_t)(parser);
    r_1 = (orbit_int)(uintptr_t)(isPrivate);
    r_2 = (orbit_int)(uintptr_t)(isExtern);
    r_3 = (void*)(uintptr_t)(parser);
    r_4 = (TokType)TokType_TAG_KeywordFn;
    r_5 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_3), (uintptr_t)(r_4)));
    r_6 = (void*)(uintptr_t)(parser);
    r_7 = (TokType)TokType_TAG_KeywordAsync;
    r_8 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_6), (uintptr_t)(r_7)));
    isAsync = (uintptr_t)(r_8);
    r_9 = (void*)(uintptr_t)(parser);
    r_10 = (TokType)TokType_TAG_Identifier;
    r_11 = (orbit_string)("Expected function name.");
    consume((void*)(uintptr_t)(r_9), (uintptr_t)(r_10), (orbit_string)(r_11));
    r_13 = (void*)(uintptr_t)(parser);
    r_14 = (void*)(uintptr_t)(((Parser*)r_13)->previousToken);
    r_15 = (orbit_string)(((Token*)r_14)->text);
    name = (uintptr_t)(r_15);
    r_16 = (void*)(uintptr_t)(parser);
    r_17 = (void*)(uintptr_t)(parseGenericParams((void*)(uintptr_t)(r_16)));
    genericParams = (uintptr_t)(r_17);
    r_18 = (void*)(uintptr_t)(parser);
    r_19 = (TokType)TokType_TAG_OpenParen;
    r_20 = (orbit_string)("Expected '(' after function name.");
    consume((void*)(uintptr_t)(r_18), (uintptr_t)(r_19), (orbit_string)(r_20));
    { OrbitResult _lr = orbit_list_create(arena, sizeof(void*), 0); r_22 = _lr.ok ? (OrbitList*)_lr.value : NULL; }
    params = (uintptr_t)(r_22);
    { OrbitResult _lr = orbit_list_create(arena, sizeof(void*), 0); r_23 = _lr.ok ? (OrbitList*)_lr.value : NULL; }
    paramTypes = (uintptr_t)(r_23);
    r_24 = (void*)(uintptr_t)(parser);
    r_25 = (TokType)TokType_TAG_CloseParen;
    r_26 = (orbit_int)(uintptr_t)(check((void*)(uintptr_t)(r_24), (uintptr_t)(r_25)));
    r_27 = (orbit_int)(uintptr_t)(false);
    r_28 = (orbit_int)(uintptr_t)(((uintptr_t)(r_26) == (uintptr_t)(r_27)));
    if (!r_28) goto label_label_352;
    r_29 = (orbit_int)(uintptr_t)(true);
    parsingParams = (uintptr_t)(r_29);
label_label_354:;
    r_30 = (void*)(uintptr_t)(parsingParams);
    if (!r_30) goto label_label_355;
    r_31 = (void*)(uintptr_t)(parser);
    r_32 = (TokType)TokType_TAG_Identifier;
    r_33 = (orbit_string)("Expected parameter name.");
    consume((void*)(uintptr_t)(r_31), (uintptr_t)(r_32), (orbit_string)(r_33));
    r_35 = (void*)(uintptr_t)(parser);
    r_36 = (void*)(uintptr_t)(((Parser*)r_35)->previousToken);
    r_37 = (orbit_string)(((Token*)r_36)->text);
    paramName = (uintptr_t)(r_37);
    r_38 = (void*)(uintptr_t)(params);
    r_39 = (orbit_string)(paramName);
    { const void* _e = &r_39; orbit_list_push(r_38, _e); }
    r_41 = (orbit_string)("unknown");
    paramType = (uintptr_t)(r_41);
    r_42 = (void*)(uintptr_t)(parser);
    r_43 = (TokType)TokType_TAG_Colon;
    r_44 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_42), (uintptr_t)(r_43)));
    if (!r_44) goto label_label_356;
    r_45 = (orbit_int)(uintptr_t)(false);
    isPointer = (uintptr_t)(r_45);
    r_46 = (void*)(uintptr_t)(parser);
    r_47 = (TokType)TokType_TAG_Ampersand;
    r_48 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_46), (uintptr_t)(r_47)));
    if (!r_48) goto label_label_358;
    r_49 = (orbit_int)(uintptr_t)(true);
    isPointer = (uintptr_t)(r_49);
    goto label_label_359;
label_label_358:;
label_label_359:;
    r_50 = (void*)(uintptr_t)(parser);
    r_51 = (orbit_string)(parseTypeName((void*)(uintptr_t)(r_50)));
    paramType = (uintptr_t)(r_51);
    r_52 = (void*)(uintptr_t)(isPointer);
    if (!r_52) goto label_label_360;
    r_53 = (orbit_string)("&");
    r_54 = (orbit_string)(paramType);
    r_55 = (void*)(uintptr_t)(orbit_string_concat(arena, (orbit_string)(r_53), (orbit_string)(r_54)));
    paramType = (uintptr_t)(r_55);
    goto label_label_361;
label_label_360:;
label_label_361:;
    goto label_label_357;
label_label_356:;
label_label_357:;
    r_56 = (void*)(uintptr_t)(paramTypes);
    r_57 = (void*)(uintptr_t)(paramType);
    { const void* _e = &r_57; orbit_list_push(r_56, _e); }
    r_59 = (void*)(uintptr_t)(parser);
    r_60 = (TokType)TokType_TAG_Comma;
    r_61 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_59), (uintptr_t)(r_60)));
    if (!r_61) goto label_label_362;
    goto label_label_363;
label_label_362:;
    r_62 = (orbit_int)(uintptr_t)(false);
    parsingParams = (uintptr_t)(r_62);
label_label_363:;
    goto label_label_354;
label_label_355:;
    goto label_label_353;
label_label_352:;
label_label_353:;
    r_63 = (void*)(uintptr_t)(parser);
    r_64 = (TokType)TokType_TAG_CloseParen;
    r_65 = (orbit_string)("Expected ')' after parameters.");
    consume((void*)(uintptr_t)(r_63), (uintptr_t)(r_64), (orbit_string)(r_65));
    r_67 = (orbit_string)("void");
    returnType = (uintptr_t)(r_67);
    r_68 = (void*)(uintptr_t)(parser);
    r_69 = (TokType)TokType_TAG_Arrow;
    r_70 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_68), (uintptr_t)(r_69)));
    if (!r_70) goto label_label_364;
    r_71 = (orbit_int)(uintptr_t)(false);
    isPointerReturn = (uintptr_t)(r_71);
    r_72 = (void*)(uintptr_t)(parser);
    r_73 = (TokType)TokType_TAG_Ampersand;
    r_74 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_72), (uintptr_t)(r_73)));
    if (!r_74) goto label_label_366;
    r_75 = (orbit_int)(uintptr_t)(true);
    isPointerReturn = (uintptr_t)(r_75);
    goto label_label_367;
label_label_366:;
label_label_367:;
    r_76 = (void*)(uintptr_t)(parser);
    r_77 = (orbit_string)(parseTypeName((void*)(uintptr_t)(r_76)));
    returnType = (uintptr_t)(r_77);
    r_78 = (void*)(uintptr_t)(isPointerReturn);
    if (!r_78) goto label_label_368;
    r_79 = (orbit_string)("&");
    r_80 = (orbit_string)(returnType);
    r_81 = (void*)(uintptr_t)(orbit_string_concat(arena, (orbit_string)(r_79), (orbit_string)(r_80)));
    returnType = (uintptr_t)(r_81);
    goto label_label_369;
label_label_368:;
label_label_369:;
    goto label_label_365;
label_label_364:;
label_label_365:;
    { OrbitResult _lr = orbit_list_create(arena, sizeof(void*), 0); r_82 = _lr.ok ? (OrbitList*)_lr.value : NULL; }
    r_83 = (void*)(uintptr_t)(BlockNode((void*)(uintptr_t)(r_82)));
    r_84 = (void*)(uintptr_t)(Block((void*)(uintptr_t)(r_83)));
    body = (uintptr_t)(r_84);
    r_85 = (void*)(uintptr_t)(parser);
    r_86 = (TokType)TokType_TAG_OpenBrace;
    r_87 = (orbit_int)(uintptr_t)(check((void*)(uintptr_t)(r_85), (uintptr_t)(r_86)));
    if (!r_87) goto label_label_370;
    r_88 = (void*)(uintptr_t)(parser);
    r_89 = (void*)(uintptr_t)(parseBlock((void*)(uintptr_t)(r_88)));
    body = (uintptr_t)(r_89);
    goto label_label_371;
label_label_370:;
    r_90 = (orbit_int)(uintptr_t)(isExtern);
    r_91 = (orbit_int)(uintptr_t)(false);
    r_92 = (orbit_int)(uintptr_t)(((uintptr_t)(r_90) == (uintptr_t)(r_91)));
