static ASTNode* parseDeclaration(Parser* parser) {
    Parser* r_0;
    Parser* r_1;
    TokType r_2;
    orbit_bool r_3;
    void* r_4;
    Parser* r_5;
    TokType r_6;
    orbit_bool r_7;
    Parser* r_8;
    orbit_string r_9;
    Parser* r_10;
    Token* r_11;
    orbit_string r_12;
    orbit_string r_13;
    void* r_14;
    Parser* r_15;
    void* r_16;
    void* r_17;
    OrbitList* r_18;
    Parser* r_19;
    TokType r_20;
    orbit_bool r_21;
    Parser* r_22;
    TokType r_23;
    orbit_bool r_24;
    Parser* r_25;
    TokType r_26;
    orbit_string r_27;
    void* r_28;
    void* r_29;
    Parser* r_30;
    Token* r_31;
    orbit_string r_32;
    OrbitList* r_33;
    void* r_34;
    void* r_35;
    Parser* r_37;
    TokType r_38;
    orbit_bool r_39;
    Parser* r_40;
    TokType r_41;
    orbit_bool r_42;
    Parser* r_43;
    TokType r_44;
    orbit_bool r_45;
    Parser* r_46;
    Token* r_47;
    orbit_string r_48;
    orbit_string r_49;
    orbit_string r_50;
    orbit_bool r_51;
    orbit_string r_52;
    orbit_string r_53;
    orbit_bool r_54;
    orbit_bool r_55;
    orbit_string r_56;
    orbit_string r_57;
    orbit_bool r_58;
    orbit_bool r_59;
    orbit_string r_60;
    orbit_string r_61;
    orbit_bool r_62;
    orbit_bool r_63;
    Parser* r_64;
    ASTNode* r_65;
    Parser* r_66;
    TokType r_67;
    orbit_bool r_68;
    Parser* r_69;
    ASTNode* r_70;
    Parser* r_71;
    TokType r_72;
    orbit_bool r_73;
    Parser* r_74;
    TokType r_75;
    orbit_string r_76;
    void* r_77;
    Parser* r_78;
    Token* r_79;
    orbit_string r_80;
    orbit_string r_81;
    void* r_82;
    void* r_83;
    Parser* r_84;
    TokType r_85;
    orbit_bool r_86;
    Parser* r_87;
    TokType r_88;
    orbit_string r_89;
    void* r_90;
    Parser* r_91;
    Token* r_92;
    orbit_string r_93;
    orbit_string r_94;
    void* r_95;
    void* r_96;
    Parser* r_97;
    TokType r_98;
    orbit_bool r_99;
    Parser* r_100;
    orbit_bool r_101;
    ASTNode* r_102;
    Parser* r_103;
    TokType r_104;
    orbit_bool r_105;
    Parser* r_106;
    void* r_107;
    ASTNode* r_108;
    Parser* r_109;
    TokType r_110;
    orbit_bool r_111;
    Parser* r_112;
    TokType r_113;
    orbit_bool r_114;
    orbit_bool r_115;
    Parser* r_116;
    orbit_bool r_117;
    orbit_bool r_118;
    ASTNode* r_119;
    Parser* r_120;
    TokType r_121;
    orbit_bool r_122;
    Parser* r_123;
    orbit_bool r_124;
    ASTNode* r_125;
    Parser* r_126;
    TokType r_127;
    orbit_bool r_128;
    Parser* r_129;
    orbit_bool r_130;
    ASTNode* r_131;
    Parser* r_132;
    TokType r_133;
    orbit_bool r_134;
    Parser* r_135;
    orbit_bool r_136;
    ASTNode* r_137;
    Parser* r_138;
    Token* r_139;
    TokType r_140;
    Parser* r_141;
    TokType r_142;
    orbit_bool r_143;
    Parser* r_144;
    TokType r_145;
    orbit_bool r_146;
    orbit_bool r_147;
    Parser* r_148;
    TokType r_149;
    orbit_bool r_150;
    orbit_bool r_151;
    Parser* r_152;
    void* r_153;
    Parser* r_154;
    TokType r_155;
    orbit_bool r_156;
    ASTNode* r_157;
    Parser* r_158;
    TokType r_159;
    orbit_bool r_160;
    Parser* r_161;
    orbit_bool r_162;
    ASTNode* r_163;
    Parser* r_164;
    TokType r_165;
    orbit_bool r_166;
    Parser* r_167;
    ASTNode* r_168;
    Parser* r_169;
    ASTNode* r_170;
    ASTNode* r_171;
    void* r_172;
    void* r_173;
    uintptr_t decorators = 0;
    uintptr_t isPrivate = 0;
    uintptr_t isExtern = 0;
    uintptr_t text = 0;
    uintptr_t path = 0;
    uintptr_t module = 0;
    uintptr_t declTag = 0;
    uintptr_t expr = 0;
    r_0 = (void*)(uintptr_t)(parser);
    r_1 = (void*)(uintptr_t)(parser);
    r_2 = (TokType)TokType_TAG_EOF;
    r_3 = (orbit_int)(uintptr_t)(check((void*)(uintptr_t)(r_1), (uintptr_t)(r_2)));
    if (!r_3) goto label_label_444;
    r_4 = (void*)(uintptr_t)(Empty());
    return (void*)(uintptr_t)(r_4);
    goto label_label_445;
label_label_444:;
label_label_445:;
    r_5 = (void*)(uintptr_t)(parser);
    r_6 = (TokType)TokType_TAG_Invalid;
    r_7 = (orbit_int)(uintptr_t)(check((void*)(uintptr_t)(r_5), (uintptr_t)(r_6)));
    if (!r_7) goto label_label_446;
    r_8 = (void*)(uintptr_t)(parser);
    r_9 = (orbit_string)("Invalid character: ");
    r_10 = (void*)(uintptr_t)(parser);
    r_11 = (void*)(uintptr_t)(((Parser*)r_10)->currentToken);
    r_12 = (orbit_string)(((Token*)r_11)->text);
    r_13 = (void*)(uintptr_t)(orbit_string_concat(arena, (orbit_string)(r_9), (orbit_string)(r_12)));
    parserError((void*)(uintptr_t)(r_8), (void*)(uintptr_t)(r_13));
    r_15 = (void*)(uintptr_t)(parser);
    advanceParser((void*)(uintptr_t)(r_15));
    r_17 = (void*)(uintptr_t)(Empty());
    return (void*)(uintptr_t)(r_17);
    goto label_label_447;
label_label_446:;
label_label_447:;
    { OrbitResult _lr = orbit_list_create(arena, sizeof(void*), 0); r_18 = _lr.ok ? (OrbitList*)_lr.value : NULL; }
    decorators = (uintptr_t)(r_18);
label_label_448:;
    r_19 = (void*)(uintptr_t)(parser);
    r_20 = (TokType)TokType_TAG_At;
    r_21 = (orbit_int)(uintptr_t)(check((void*)(uintptr_t)(r_19), (uintptr_t)(r_20)));
    if (!r_21) goto label_label_449;
    r_22 = (void*)(uintptr_t)(parser);
    r_23 = (TokType)TokType_TAG_At;
    r_24 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_22), (uintptr_t)(r_23)));
    r_25 = (void*)(uintptr_t)(parser);
    r_26 = (TokType)TokType_TAG_Identifier;
    r_27 = (orbit_string)("Expected decorator name.");
    consume((void*)(uintptr_t)(r_25), (uintptr_t)(r_26), (orbit_string)(r_27));
    r_29 = (void*)(uintptr_t)(decorators);
    r_30 = (void*)(uintptr_t)(parser);
    r_31 = (void*)(uintptr_t)(((Parser*)r_30)->previousToken);
    r_32 = (orbit_string)(((Token*)r_31)->text);
    { OrbitResult _lr = orbit_list_create(arena, sizeof(void*), 0); r_33 = _lr.ok ? (OrbitList*)_lr.value : NULL; }
    r_34 = (void*)(uintptr_t)(DecoratorNode((void*)(uintptr_t)(r_32), (void*)(uintptr_t)(r_33)));
    r_35 = (void*)(uintptr_t)(Decorator((void*)(uintptr_t)(r_34)));
    { const void* _e = &r_35; orbit_list_push(r_29, _e); }
    goto label_label_448;
label_label_449:;
    r_37 = (void*)(uintptr_t)(parser);
    r_38 = (TokType)TokType_TAG_KeywordPrivate;
    r_39 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_37), (uintptr_t)(r_38)));
    isPrivate = (uintptr_t)(r_39);
    r_40 = (void*)(uintptr_t)(parser);
    r_41 = (TokType)TokType_TAG_KeywordExtern;
    r_42 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_40), (uintptr_t)(r_41)));
    isExtern = (uintptr_t)(r_42);
    r_43 = (void*)(uintptr_t)(parser);
    r_44 = (TokType)TokType_TAG_Identifier;
    r_45 = (orbit_int)(uintptr_t)(check((void*)(uintptr_t)(r_43), (uintptr_t)(r_44)));
    if (!r_45) goto label_label_450;
    r_46 = (void*)(uintptr_t)(parser);
    r_47 = (void*)(uintptr_t)(((Parser*)r_46)->currentToken);
    r_48 = (orbit_string)(((Token*)r_47)->text);
    text = (uintptr_t)(r_48);
    r_49 = (orbit_string)(text);
    r_50 = (orbit_string)("port");
    r_51 = (orbit_int)(uintptr_t)(((orbit_string)(r_49) != NULL && (orbit_string)(r_50) != NULL ? strcmp((orbit_string)(r_49), (orbit_string)(r_50)) == 0 : (uintptr_t)(r_49) == (uintptr_t)(r_50)));
    r_52 = (orbit_string)(text);
    r_53 = (orbit_string)("cors");
    r_54 = (orbit_int)(uintptr_t)(((orbit_string)(r_52) != NULL && (orbit_string)(r_53) != NULL ? strcmp((orbit_string)(r_52), (orbit_string)(r_53)) == 0 : (uintptr_t)(r_52) == (uintptr_t)(r_53)));
    r_55 = (r_51 || r_54);
    r_56 = (orbit_string)(text);
    r_57 = (orbit_string)("db");
    r_58 = (orbit_int)(uintptr_t)(((orbit_string)(r_56) != NULL && (orbit_string)(r_57) != NULL ? strcmp((orbit_string)(r_56), (orbit_string)(r_57)) == 0 : (uintptr_t)(r_56) == (uintptr_t)(r_57)));
    r_59 = (r_55 || r_58);
    r_60 = (orbit_string)(text);
    r_61 = (orbit_string)("env");
    r_62 = (orbit_int)(uintptr_t)(((orbit_string)(r_60) != NULL && (orbit_string)(r_61) != NULL ? strcmp((orbit_string)(r_60), (orbit_string)(r_61)) == 0 : (uintptr_t)(r_60) == (uintptr_t)(r_61)));
    r_63 = (r_59 || r_62);
    if (!r_63) goto label_label_452;
    r_64 = (void*)(uintptr_t)(parser);
    r_65 = (void*)(uintptr_t)(parseConfigDecl((void*)(uintptr_t)(r_64)));
    return (void*)(uintptr_t)(r_65);
    goto label_label_453;
label_label_452:;
label_label_453:;
    goto label_label_451;
label_label_450:;
label_label_451:;
    r_66 = (void*)(uintptr_t)(parser);
    r_67 = (TokType)TokType_TAG_KeywordEvery;
    r_68 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_66), (uintptr_t)(r_67)));
    if (!r_68) goto label_label_454;
    r_69 = (void*)(uintptr_t)(parser);
    r_70 = (void*)(uintptr_t)(parseScheduleDecl((void*)(uintptr_t)(r_69)));
    return (void*)(uintptr_t)(r_70);
    goto label_label_455;
label_label_454:;
label_label_455:;
    r_71 = (void*)(uintptr_t)(parser);
    r_72 = (TokType)TokType_TAG_KeywordImport;
    r_73 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_71), (uintptr_t)(r_72)));
    if (!r_73) goto label_label_456;
    r_74 = (void*)(uintptr_t)(parser);
    r_75 = (TokType)TokType_TAG_StringLiteral;
    r_76 = (orbit_string)("Expected import path.");
    consume((void*)(uintptr_t)(r_74), (uintptr_t)(r_75), (orbit_string)(r_76));
    r_78 = (void*)(uintptr_t)(parser);
    r_79 = (void*)(uintptr_t)(((Parser*)r_78)->previousToken);
    r_80 = (orbit_string)(((Token*)r_79)->text);
    path = (uintptr_t)(r_80);
    r_81 = (orbit_string)(path);
    r_82 = (void*)(uintptr_t)(ImportStmtNode((void*)(uintptr_t)(r_81)));
    r_83 = (void*)(uintptr_t)(ImportStmt((void*)(uintptr_t)(r_82)));
    return (void*)(uintptr_t)(r_83);
    goto label_label_457;
label_label_456:;
label_label_457:;
    r_84 = (void*)(uintptr_t)(parser);
    r_85 = (TokType)TokType_TAG_KeywordUse;
    r_86 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_84), (uintptr_t)(r_85)));
    if (!r_86) goto label_label_458;
    r_87 = (void*)(uintptr_t)(parser);
    r_88 = (TokType)TokType_TAG_Identifier;
    r_89 = (orbit_string)("Expected module name.");
    consume((void*)(uintptr_t)(r_87), (uintptr_t)(r_88), (orbit_string)(r_89));
    r_91 = (void*)(uintptr_t)(parser);
    r_92 = (void*)(uintptr_t)(((Parser*)r_91)->previousToken);
    r_93 = (orbit_string)(((Token*)r_92)->text);
    module = (uintptr_t)(r_93);
    r_94 = (orbit_string)(module);
    r_95 = (void*)(uintptr_t)(UseStmtNode((void*)(uintptr_t)(r_94)));
    r_96 = (void*)(uintptr_t)(UseStmt((void*)(uintptr_t)(r_95)));
    return (void*)(uintptr_t)(r_96);
    goto label_label_459;
label_label_458:;
label_label_459:;
    r_97 = (void*)(uintptr_t)(parser);
    r_98 = (TokType)TokType_TAG_KeywordModel;
    r_99 = (orbit_int)(uintptr_t)(matchToken((void*)(uintptr_t)(r_97), (uintptr_t)(r_98)));
    if (!r_99) goto label_label_460;
    r_100 = (void*)(uintptr_t)(parser);
